#!/bin/bash
set -u

function usage() {
	echo "Usage:"
	echo "    bash ./install --prefix=\$YOUR_PATH";
	exit 1
}

NGINX_INSTALL_STATE=/tmp/nginx.install.state
PHP_INSTALL_STATE=/tmp/php.install.state
YAF_INSTALL_STATE=/tmp/yaf.install.state
CURL_INSTALL_STATE=/tmp/curl.install.state
MSGPACK_INSTALL_STATE=/tmp/msgpack.install.state
MBSTRING_INSTALL_STATE=/tmp/mbstring.install.state
REDIS_INSTALL_STATE=/tmp/redis.install.state
GD_INSTALL_STATE=/tmp/gd.install.state
PHP_OPENSSL_INSTALL_STATE=/tmp/phpopenssl.install.state
ZLIB_INSTALL_STATE=/tmp/zlib.install.state
ZIP_INSTALL_STATE=/tmp/zip.install.state
PCRE_INSTALL_STATE=/tmp/pcre.install.state
OPENSSL_INSTALL_STATE=/tmp/openssl.install.state

LOG=/tmp/install.log
WF_LOG=/tmp/install.log.wf

function init(){
	touch $LOG
	touch $WF_LOG
	cat /dev/null > $LOG
	cat /dev/null > $WF_LOG

    touch $NGINX_INSTALL_STATE
    touch $PHP_INSTALL_STATE
    touch $YAF_INSTALL_STATE
    touch $CURL_INSTALL_STATE
    touch $MSGPACK_INSTALL_STATE
    touch $MBSTRING_INSTALL_STATE
    touch $REDIS_INSTALL_STATE
    touch $GD_INSTALL_STATE
    touch $PHP_OPENSSL_INSTALL_STATE
    touch $ZLIB_INSTALL_STATE
    touch $ZIP_INSTALL_STATE
    touch $PCRE_INSTALL_STATE
    touch $OPENSSL_INSTALL_STATE
    echo '-' > $NGINX_INSTALL_STATE
    echo '-' > $PHP_INSTALL_STATE
    echo '-' > $YAF_INSTALL_STATE
    echo '-' > $CURL_INSTALL_STATE
    echo '-' > $MSGPACK_INSTALL_STATE
    echo '-' > $MBSTRING_INSTALL_STATE
    echo '-' > $REDIS_INSTALL_STATE
    echo '-' > $GD_INSTALL_STATE
    echo '-' > $PHP_OPENSSL_INSTALL_STATE
    echo '-' > $ZLIB_INSTALL_STATE
    echo '-' > $ZIP_INSTALL_STATE
    echo '-' > $PCRE_INSTALL_STATE
    echo '-' > $OPENSSL_INSTALL_STATE
}

function install_nginx(){
	{
		_PCRE_DIR=/tmp/pcre

		pushd $PWD >/dev/null
		cd package 2>>$WF_LOG
	
		_TAR=$(ls pcre*.tar.gz 2>>$WF_LOG);
		mkdir -p $_PCRE_DIR 2>>$WF_LOG && tar zxf $_TAR -C $_PCRE_DIR 2>>$WF_LOG
	
		_PCRE_DIR=$_PCRE_DIR/$(ls $_PCRE_DIR);
		popd >/dev/null

		_OPENSSL_DIR=/tmp/openssl
	
		pushd $PWD >/dev/null
		cd package 2>>$WF_LOG
	
		_TAR=$(ls openssl*.tar.gz 2>>$WF_LOG);
		mkdir -p $_OPENSSL_DIR 2>>$WF_LOG && tar zxf $_TAR -C $_OPENSSL_DIR 2>>$WF_LOG
	
		_OPENSSL_DIR=$_OPENSSL_DIR/$(ls $_OPENSSL_DIR);
		popd >/dev/null

		_DIR=/tmp/nginx
	
		pushd $PWD >/dev/null
		cd package 2>>$WF_LOG
	
		_TAR=$(ls nginx*.tar.gz 2>>$WF_LOG);
		mkdir -p $_DIR 2>>$WF_LOG && tar zxf $_TAR -C $_DIR 2>>$WF_LOG
	
		_DIR=$_DIR/$(ls $_DIR);
		cd $_DIR 2>>$WF_LOG
		./configure --prefix=${PREFIX}/webserver --with-http_ssl_module --with-pcre=$_PCRE_DIR --with-openssl=$_OPENSSL_DIR 1>>$LOG 2>>$WF_LOG
        if [ $? != 0 ]; then
            echo 'configure error see '$LOG >> $WF_LOG
        fi
		
		if [ $(uname) == 'Darwin' ]; then
		    make 1>>$LOG 2>/dev/null && make install 1>>$LOG 2>>$WF_LOG
		else
		    make 1>>$LOG 2>>$WF_LOG && make install 1>>$LOG 2>>$WF_LOG
            if [ $? != 0 ]; then
                echo 'make error see '$WF_LOG >> $WF_LOG
            fi
		fi
        
		popd >/dev/null
		cp tpl/nginx.conf ${PREFIX}/webserver/conf
		cp tpl/nginx_control ${PREFIX}/webserver
		cp tpl/fastcgi.conf ${PREFIX}/webserver/conf
		cp tpl/fastcgi_params ${PREFIX}/webserver/conf

		if [ $(uname) == 'Darwin' ]; then
			sed -i "" "s|\${PEQ_ROOT}|${PREFIX}|g" $PREFIX/webserver/conf/nginx.conf 1>>$LOG 2>>$WF_LOG
			sed -i "" "s|\${PEQ_ROOT}|${PREFIX}|g" $PREFIX/webserver/nginx_control 1>>$LOG 2>>$WF_LOG
		else
			sed -i "s|\${PEQ_ROOT}|${PREFIX}|g" $PREFIX/webserver/conf/nginx.conf 1>>$LOG 2>>$WF_LOG
			sed -i "s|\${PEQ_ROOT}|${PREFIX}|g" $PREFIX/webserver/nginx_control 1>>$LOG 2>>$WF_LOG
		fi

		echo $? > $NGINX_INSTALL_STATE
	}&
	
	NGINX_IS_DONE="0"
	while :
	do
		for j in '-' '\\' '|' '/'; do
			tput sc
			echo -ne  "Installing Nginx, Please wait....... $j"
			sleep 0.1
			tput rc
			
			if [ -s "$WF_LOG" ]; then
				echo "Sth wrong, Please check $LOG and $WF_LOG"
                echo '-' > $NGINX_INSTALL_STATE
				NGINX_IS_DONE="2"
				break
			fi
			if [ -f "$NGINX_INSTALL_STATE" ] && [ $(cat $NGINX_INSTALL_STATE) == '0' ]; then
				echo "Install Nginx Done                          "
                echo '-' > $NGINX_INSTALL_STATE
				NGINX_IS_DONE="1"
				break
			fi
		done
		if [ "$NGINX_IS_DONE" = "1" ] || [ "$NGINX_IS_DONE" = "2" ]; then
			break
		fi
	done
}

function install_php(){
	{
		_DIR=/tmp/php

		pushd $PWD >/dev/null
		cd package 2>>$WF_LOG

		_TAR=$(ls php*.tar.gz 2>>$WF_LOG);
		mkdir -p $_DIR 2>>$WF_LOG && tar zxf $_TAR -C $_DIR 2>>$WF_LOG

		_DIR=$_DIR/$(ls $_DIR);
		cd $_DIR 2>>$WF_LOG

		if [ $(uname) == 'Darwin' ]; then
			./configure --prefix=${PREFIX}/php --without-iconv --with-mysqli --with-pdo-mysql --with-config-file-scan-dir=${PREFIX}/php/etc/ext --with-config-file-path=${PREFIX}/php/etc --enable-fpm --disable-phar CFLAGS="-Wno-logical-op-parentheses -Wno-return-type -Wno-macro-redefined -Wno-enum-conversion -Wno-logical-not-parentheses -Wno-tautological-compare -Wno-string-plus-int -Wno-gnu-statement-expression -Wno-absolute-value -Wno-format -Wno-pointer-bool-conversion -Wno-incompatible-pointer-types-discards-qualifiers -Wno-format-extra-args -Wno-format-invalid-specifier -Wno-deprecated-declarations -Wno-pointer-sign -Wno-empty-body" 1>>$LOG 2>&1
		else
			./configure --prefix=${PREFIX}/php --with-mysqli --with-pdo-mysql --with-config-file-scan-dir=${PREFIX}/php/etc/ext --with-config-file-path=${PREFIX}/php/etc --enable-fpm --disable-phar CFLAGS="-w" 1>>$LOG 2>&1
		fi

        if [ $? != 0 ]; then
            echo 'configure error see '$LOG >> $WF_LOG
        fi

		if [ $(uname) == 'Darwin' ]; then
		    make 1>>$LOG 2>&1 && make install 1>>$LOG 2>>$WF_LOG
		else
		    make 1>>$LOG 2>>$WF_LOG && make install 1>>$LOG 2>>$WF_LOG
        fi
        if [ $? != 0 ]; then
            echo 'make error see '$WF_LOG >> $WF_LOG
        fi
		popd >/dev/null

		#mv ${PREFIX}/php/etc/php-fpm.conf ${PREFIX}/php/etc/php-fpm.conf
		#mv ${PREFIX}/php/etc/php-fpm.d/www.conf ${PREFIX}/php/etc/php-fpm.d/www.conf

		cp tpl/php.ini $PREFIX/php/etc 
		cp tpl/php-fpm_control ${PREFIX}/php 
		cp tpl/php-fpm.conf ${PREFIX}/php/etc 
		cp tpl/www.conf ${PREFIX}/php/etc/php-fpm.d/

		if [ $(uname) == 'Darwin' ]; then
			sed -i "" "s|\${PEQ_ROOT}|${PREFIX}|g" $PREFIX/php/etc/php.ini 1>>$LOG 2>>$WF_LOG
			sed -i "" "s|\${PEQ_ROOT}|${PREFIX}|g" ${PREFIX}/php/php-fpm_control 1>>$LOG 2>>$WF_LOG
			sed -i "" "s|\${PEQ_ROOT}|${PREFIX}|g" ${PREFIX}/php/etc/php-fpm.conf 1>>$LOG 2>>$WF_LOG
			sed -i "" "s|\${PEQ_ROOT}|${PREFIX}|g" ${PREFIX}/php/etc/php-fpm.d/www.conf 1>>$LOG 2>>$WF_LOG
		else
			sed -i "s|\${PEQ_ROOT}|${PREFIX}|g" $PREFIX/php/etc/php.ini 1>>$LOG 2>>$WF_LOG
			sed -i "s|\${PEQ_ROOT}|${PREFIX}|g" ${PREFIX}/php/php-fpm_control 1>>$LOG 2>>$WF_LOG
			sed -i "s|\${PEQ_ROOT}|${PREFIX}|g" ${PREFIX}/php/etc/php-fpm.conf 1>>$LOG 2>>$WF_LOG
			sed -i "s|\${PEQ_ROOT}|${PREFIX}|g" ${PREFIX}/php/etc/php-fpm.d/www.conf 1>>$LOG 2>>$WF_LOG
		fi

		echo $? > $PHP_INSTALL_STATE
	}&

	PHP_IS_DONE="0"
	while :
	do
		for j in '-' '\\' '|' '/'; do
			tput sc
			echo -ne  "Installing PHP, Please wait....... $j"
			sleep 0.1
			tput rc
			
			if [ -s "$WF_LOG" ]; then
				echo "Sth wrong, Please check $LOG and $WF_LOG"
                echo '-' > $PHP_INSTALL_STATE
				PHP_IS_DONE="2"
				break
			fi
			if [ -f "$PHP_INSTALL_STATE" ] && [ $(cat $PHP_INSTALL_STATE) == '0' ]; then
				echo "Install PHP Done                          "
                echo '-' > $PHP_INSTALL_STATE
				PHP_IS_DONE="1"
				break
			fi
		done
		if [ "$PHP_IS_DONE" = "1" ] || [ "$PHP_IS_DONE" = "2" ]; then
		    break
		fi
	done
}

function install_yaf(){
	{
		sleep 3

		_DIR=/tmp/yaf

		pushd $PWD >/dev/null
		cd package 2>>$WF_LOG

		_TAR=$(ls yaf*.tgz 2>>$WF_LOG);
		mkdir -p $_DIR 2>>$WF_LOG && tar zxf $_TAR -C $_DIR 2>>$WF_LOG

		_DIR=$_DIR/$(ls $_DIR | grep yaf)
		cd $_DIR 2>>$WF_LOG
		${PREFIX}/php/bin/phpize 1>>$LOG 2>>$WF_LOG
		if [ $(uname) == 'Darwin' ]; then
			./configure --with-php-config=${PREFIX}/php/bin/php-config CFLAGS="-Wno-logical-op-parentheses -Wno-return-type -Wno-macro-redefined -Wno-enum-conversion -Wno-logical-not-parentheses -Wno-tautological-compare -Wno-string-plus-int -Wno-gnu-statement-expression -Wno-absolute-value -Wno-format -Wno-pointer-bool-conversion -Wno-incompatible-pointer-types-discards-qualifiers -Wno-format-extra-args -Wno-format-invalid-specifier -Wno-deprecated-declarations -Wno-pointer-sign -Wno-empty-body" 1>>$LOG 2>&1
		else
		    ./configure --with-php-config=${PREFIX}/php/bin/php-config CFLAGS="-w" 1>>$LOG 2>&1
		fi
        if [ $? != 0 ]; then
            echo 'configure error see '$LOG >> $WF_LOG
        fi
		
		if [ $(uname) == 'Darwin' ]; then
		    make 1>>$LOG 2>&1 && make install 1>>$LOG 2>>$WF_LOG
        else
		    make 1>>$LOG 2>>$WF_LOG && make install 1>>$LOG 2>>$WF_LOG
        fi
        if [ $? != 0 ]; then
            echo 'make error see '$WF_LOG >> $WF_LOG
        fi

		popd >/dev/null

		cp tpl/yaf.ini $PREFIX/php/etc/ext

		if [ $(uname) == 'Darwin' ]; then
			sed -i "" "s|\${PEQ_ROOT}|${PREFIX}|g" $PREFIX/php/etc/ext/yaf.ini 1>>$LOG 2>>$WF_LOG
		else
			sed -i "s|\${PEQ_ROOT}|${PREFIX}|g" $PREFIX/php/etc/ext/yaf.ini 1>>$LOG 2>>$WF_LOG
		fi

		echo $? > $YAF_INSTALL_STATE
	}&

	YAF_IS_DONE="0"
	while :
	do
		for j in '-' '\\' '|' '/'; do
			tput sc
			echo -ne  "Installing Yaf, Please wait....... $j"
			sleep 0.1
			tput rc
			
			if [ -s "$WF_LOG" ]; then
				echo "Sth wrong, Please check $LOG and $WF_LOG"
                echo '-' > $YAF_INSTALL_STATE
				YAF_IS_DONE="2"
				break
			fi
			if [ -f "$YAF_INSTALL_STATE" ] && [ $(cat $YAF_INSTALL_STATE) != '-' ]; then
				echo "Install yaf Done                          "
                echo '-' > $YAF_INSTALL_STATE
				YAF_IS_DONE="1"
				break
			fi
		done
		if [ "$YAF_IS_DONE" = "1" ] || [ "$YAF_IS_DONE" = "2" ]; then
			break
		fi
	done
}

function install_msgpack(){
	{
		sleep 3

		_DIR=/tmp/msgpack

		pushd $PWD >/dev/null
		cd package 2>>$WF_LOG

		_TAR=$(ls msgpack*.tgz 2>>$WF_LOG);
		mkdir -p $_DIR 2>>$WF_LOG && tar zxf $_TAR -C $_DIR 2>>$WF_LOG

		_DIR=$_DIR/$(ls $_DIR | grep msgpack)
		cd $_DIR 2>>$WF_LOG
		${PREFIX}/php/bin/phpize  1>>$LOG 2>>$WF_LOG
		if [ $(uname) == 'Darwin' ]; then
			./configure --with-php-config=${PREFIX}/php/bin/php-config CFLAGS="-Wno-logical-op-parentheses -Wno-return-type -Wno-macro-redefined -Wno-enum-conversion -Wno-logical-not-parentheses -Wno-tautological-compare -Wno-string-plus-int -Wno-gnu-statement-expression -Wno-absolute-value -Wno-format -Wno-pointer-bool-conversion -Wno-incompatible-pointer-types-discards-qualifiers -Wno-format-extra-args -Wno-format-invalid-specifier -Wno-deprecated-declarations -Wno-pointer-sign -Wno-empty-body" 1>>$LOG 2>&1
		else
		    ./configure --with-php-config=${PREFIX}/php/bin/php-config CFLAGS="-w" 1>>$LOG 2>&1
		fi
        if [ $? != 0 ]; then
            echo 'configure error see '$LOG >> $WF_LOG
        fi

		if [ $(uname) == 'Darwin' ]; then
		    make 1>>$LOG 2>&1 && make install 1>>$LOG 2>>$WF_LOG
        else
		    make 1>>$LOG 2>>$WF_LOG && make install 1>>$LOG 2>>$WF_LOG
        fi

        if [ $? != 0 ]; then
            echo 'make error see '$WF_LOG >> $WF_LOG
        fi

		popd >/dev/null

		cp tpl/msgpack.ini $PREFIX/php/etc/ext

		echo $? > $MSGPACK_INSTALL_STATE
	}&

	MSGPACK_IS_DONE="0"
	while :
	do
		for j in '-' '\\' '|' '/'; do
			tput sc
			echo -ne  "Installing msgpack, Please wait....... $j"
			sleep 0.1
			tput rc
			
			if [ -s "$WF_LOG" ]; then
				echo "Sth wrong, Please check $LOG and $WF_LOG"
                echo '-' > $MSGPACK_INSTALL_STATE
				MSGPACK_IS_DONE="2"
				break
			fi
			if [ -f "$MSGPACK_INSTALL_STATE" ] && [ $(cat $MSGPACK_INSTALL_STATE) != '-' ]; then
				echo "Install msgpack Done                          "
                echo '-' > $MSGPACK_INSTALL_STATE
				MSGPACK_IS_DONE="1"
				break
			fi
		done
		if [ "$MSGPACK_IS_DONE" = "1" ] || [ "$MSGPACK_IS_DONE" = "2" ]; then
			break
		fi
	done
}

function install_redis(){
	{
		sleep 3

		_DIR=/tmp/redis

		pushd $PWD >/dev/null
		cd package 2>>$WF_LOG

		_TAR=$(ls redis*.tgz 2>>$WF_LOG);
		mkdir -p $_DIR 2>>$WF_LOG && tar zxf $_TAR -C $_DIR 2>>$WF_LOG

		_DIR=$_DIR/$(ls $_DIR | grep redis)
		cd $_DIR 2>>$WF_LOG
		${PREFIX}/php/bin/phpize  1>>$LOG 2>>$WF_LOG
		if [ $(uname) == 'Darwin' ]; then
			./configure --with-php-config=${PREFIX}/php/bin/php-config CFLAGS="-Wno-logical-op-parentheses -Wno-return-type -Wno-macro-redefined -Wno-enum-conversion -Wno-logical-not-parentheses -Wno-tautological-compare -Wno-string-plus-int -Wno-gnu-statement-expression -Wno-absolute-value -Wno-format -Wno-pointer-bool-conversion -Wno-incompatible-pointer-types-discards-qualifiers -Wno-format-extra-args -Wno-format-invalid-specifier -Wno-deprecated-declarations -Wno-pointer-sign -Wno-empty-body" 1>>$LOG 2>&1
		else
		    ./configure --with-php-config=${PREFIX}/php/bin/php-config CFLAGS="-w" 1>>$LOG 2>&1
		fi
        if [ $? != 0 ]; then
            echo 'configure error see '$LOG >> $WF_LOG
        fi
		
		if [ $(uname) == 'Darwin' ]; then
		    make 1>>$LOG 2>&1 && make install 1>>$LOG 2>>$WF_LOG
        else
		    make 1>>$LOG 2>>$WF_LOG && make install 1>>$LOG 2>>$WF_LOG
        fi

        if [ $? != 0 ]; then
            echo 'make error see '$WF_LOG >> $WF_LOG
        fi

		popd >/dev/null

		cp tpl/redis.ini $PREFIX/php/etc/ext

		echo $? > $REDIS_INSTALL_STATE
	}&

	REDIS_IS_DONE="0"
	while :
	do
		for j in '-' '\\' '|' '/'; do
			tput sc
			echo -ne  "Installing redis, Please wait....... $j"
			sleep 0.1
			tput rc
			
			if [ -s "$WF_LOG" ]; then
				echo "Sth wrong, Please check $LOG and $WF_LOG"
                echo '-' > $REDIS_INSTALL_STATE
				REDIS_IS_DONE="2"
				break
			fi
			if [ -f "$REDIS_INSTALL_STATE" ] && [ $(cat $REDIS_INSTALL_STATE) != '-' ]; then
				echo "Install redis Done                          "
                echo '-' > $REDIS_INSTALL_STATE
				REDIS_IS_DONE="1"
				break
			fi
		done
		if [ "$REDIS_IS_DONE" = "1" ] || [ "$REDIS_IS_DONE" = "2" ]; then
			break
		fi
	done
}

function install_curl(){
	{
		sleep 3

		pushd $PWD >/dev/null
		cd /tmp/php/php* 2>>$WF_LOG

		cd ext/curl 2>>$WF_LOG
		${PREFIX}/php/bin/phpize  1>>$LOG 2>>$WF_LOG
		if [ $(uname) == 'Darwin' ]; then
			./configure --with-php-config=${PREFIX}/php/bin/php-config --with-curl=/usr/local/opt/curl CFLAGS="-Wno-logical-op-parentheses -Wno-return-type -Wno-macro-redefined -Wno-enum-conversion -Wno-logical-not-parentheses -Wno-tautological-compare -Wno-string-plus-int -Wno-gnu-statement-expression -Wno-absolute-value -Wno-format -Wno-pointer-bool-conversion -Wno-incompatible-pointer-types-discards-qualifiers -Wno-format-extra-args -Wno-format-invalid-specifier -Wno-deprecated-declarations -Wno-pointer-sign -Wno-empty-body" 1>>$LOG 2>&1
		else
		    ./configure --with-php-config=${PREFIX}/php/bin/php-config CFLAGS="-w" 1>>$LOG 2>&1
		fi
        if [ $? != 0 ]; then
            echo 'configure error see '$LOG >> $WF_LOG
        fi
		
		if [ $(uname) == 'Darwin' ]; then
		    make 1>>$LOG 2>&1 && make install 1>>$LOG 2>>$WF_LOG
        else
		    make 1>>$LOG 2>>$WF_LOG && make install 1>>$LOG 2>>$WF_LOG
        fi

        if [ $? != 0 ]; then
            echo 'make error see '$WF_LOG >> $WF_LOG
        fi

		popd >/dev/null

		cp tpl/curl.ini $PREFIX/php/etc/ext

		echo $? > $CURL_INSTALL_STATE
	}&

	CURL_IS_DONE="0"
	while :
	do
		for j in '-' '\\' '|' '/'; do
			tput sc
			echo -ne  "Installing cURL, Please wait....... $j"
		    sleep 0.1
		    tput rc
		    
			if [ -s "$WF_LOG" ]; then
				echo "Sth wrong, Please check $LOG and $WF_LOG"
                echo '-' > $CURL_INSTALL_STATE
				CURL_IS_DONE="2"
				break
			fi
			if [ -f "$CURL_INSTALL_STATE" ] && [ $(cat $CURL_INSTALL_STATE) != '-' ]; then
				echo "Install cURL Done                          "
                echo '-' > $CURL_INSTALL_STATE
				CURL_IS_DONE="1"
				break
			fi
		done
		if [ "$CURL_IS_DONE" = "1" ] || [ "$CURL_IS_DONE" = "2" ]; then
			break
		fi
	done
}

function install_mbstring(){
	{
		sleep 3

		pushd $PWD >/dev/null
		cd /tmp/php/php* 2>>$WF_LOG

		cd ext/mbstring 2>>$WF_LOG
		${PREFIX}/php/bin/phpize  1>>$LOG 2>>$WF_LOG
		if [ $(uname) == 'Darwin' ]; then
			./configure --with-php-config=${PREFIX}/php/bin/php-config CFLAGS="-Wno-logical-op-parentheses -Wno-return-type -Wno-macro-redefined -Wno-enum-conversion -Wno-logical-not-parentheses -Wno-tautological-compare -Wno-string-plus-int -Wno-gnu-statement-expression -Wno-absolute-value -Wno-format -Wno-pointer-bool-conversion -Wno-incompatible-pointer-types-discards-qualifiers -Wno-format-extra-args -Wno-format-invalid-specifier -Wno-deprecated-declarations -Wno-pointer-sign -Wno-empty-body" 1>>$LOG 2>&1
		else
		    ./configure --with-php-config=${PREFIX}/php/bin/php-config CFLAGS="-w" 1>>$LOG 2>&1
		fi
        if [ $? != 0 ]; then
            echo 'configure error see '$LOG >> $WF_LOG
        fi
		
		if [ $(uname) == 'Darwin' ]; then
		    make 1>>$LOG 2>&1 && make install 1>>$LOG 2>>$WF_LOG
        else
		    make 1>>$LOG 2>>$WF_LOG && make install 1>>$LOG 2>>$WF_LOG
        fi

        if [ $? != 0 ]; then
            echo 'make error see '$WF_LOG >> $WF_LOG
        fi

		popd >/dev/null

		cp tpl/mbstring.ini $PREFIX/php/etc/ext

		echo $? > $MBSTRING_INSTALL_STATE
	}&

	MBSTRING_IS_DONE="0"
	while :
	do
		for j in '-' '\\' '|' '/'; do
			tput sc
			echo -ne  "Installing mbstring, Please wait....... $j"
		    sleep 0.1
		    tput rc
		    
			if [ -s "$WF_LOG" ]; then
				echo "Sth wrong, Please check $LOG and $WF_LOG"
                echo '-' > $MBSTRING_INSTALL_STATE
				MBSTRING_IS_DONE="2"
				break
			fi
			if [ -f "$MBSTRING_INSTALL_STATE" ] && [ $(cat $MBSTRING_INSTALL_STATE) != '-' ]; then
				echo "Install mbstring Done                          "
                echo '-' > $MBSTRING_INSTALL_STATE
				MBSTRING_IS_DONE="1"
				break
			fi
		done
		if [ "$MBSTRING_IS_DONE" = "1" ] || [ "$MBSTRING_IS_DONE" = "2" ]; then
			break
		fi
	done
}

function install_phpopenssl(){
	{
		sleep 3

		pushd $PWD >/dev/null
		cd /tmp/php/php* 2>>$WF_LOG

		cd ext/openssl 2>>$WF_LOG

        cp config0.m4 config.m4

		${PREFIX}/php/bin/phpize  1>>$LOG 2>>$WF_LOG
		if [ $(uname) == 'Darwin' ]; then
			./configure --with-php-config=${PREFIX}/php/bin/php-config --with-openssl=/usr/local/opt/openssl CFLAGS="-Wno-logical-op-parentheses -Wno-return-type -Wno-macro-redefined -Wno-enum-conversion -Wno-logical-not-parentheses -Wno-tautological-compare -Wno-string-plus-int -Wno-gnu-statement-expression -Wno-absolute-value -Wno-format -Wno-pointer-bool-conversion -Wno-incompatible-pointer-types-discards-qualifiers -Wno-format-extra-args -Wno-format-invalid-specifier -Wno-deprecated-declarations -Wno-pointer-sign -Wno-empty-body" 1>>$LOG 2>&1
		else
		    ./configure --with-php-config=${PREFIX}/php/bin/php-config CFLAGS="-w" 1>>$LOG 2>&1
            if [ $? != 0 ]; then
                echo 'configure error see '$LOG >> $WF_LOG
            fi
		fi
		
		if [ $(uname) == 'Darwin' ]; then
		    make 1>>$LOG 2>&1 && make install 1>>$LOG 2>>$WF_LOG
        else
		    make 1>>$LOG 2>>$WF_LOG && make install 1>>$LOG 2>>$WF_LOG
        fi

        if [ $? != 0 ]; then
            echo 'make error see '$WF_LOG >> $WF_LOG
        fi

		popd >/dev/null

		cp tpl/openssl.ini $PREFIX/php/etc/ext

		echo $? > $PHP_OPENSSL_INSTALL_STATE
	}&

	PHP_OPENSSL_IS_DONE="0"
	while :
	do
		for j in '-' '\\' '|' '/'; do
			tput sc
			echo -ne  "Installing openssl, Please wait....... $j"
		    sleep 0.1
		    tput rc
		    
			if [ -s "$WF_LOG" ]; then
				echo "Sth wrong, Please check $LOG and $WF_LOG"
                echo '-' > $PHP_OPENSSL_INSTALL_STATE
				PHP_OPENSSL_IS_DONE="2"
				break
			fi
			if [ -f "$PHP_OPENSSL_INSTALL_STATE" ] && [ $(cat $PHP_OPENSSL_INSTALL_STATE) != '-' ]; then
				echo "Install openssl Done                          "
                echo '-' > $PHP_OPENSSL_INSTALL_STATE
				PHP_OPENSSL_IS_DONE="1"
				break
			fi
		done
		if [ "$PHP_OPENSSL_IS_DONE" = "1" ] || [ "$PHP_OPENSSL_IS_DONE" = "2" ]; then
			break
		fi
	done
}

function install_zlib(){
	{
		sleep 3

		pushd $PWD >/dev/null
		cd /tmp/php/php* 2>>$WF_LOG

		cd ext/zlib 2>>$WF_LOG

        cp config0.m4 config.m4

		${PREFIX}/php/bin/phpize  1>>$LOG 2>>$WF_LOG
		if [ $(uname) == 'Darwin' ]; then
			./configure --with-php-config=${PREFIX}/php/bin/php-config --with-zlib=/usr/local/opt/zlib/ CFLAGS="-Wno-logical-op-parentheses -Wno-return-type -Wno-macro-redefined -Wno-enum-conversion -Wno-logical-not-parentheses -Wno-tautological-compare -Wno-string-plus-int -Wno-gnu-statement-expression -Wno-absolute-value -Wno-format -Wno-pointer-bool-conversion -Wno-incompatible-pointer-types-discards-qualifiers -Wno-format-extra-args -Wno-format-invalid-specifier -Wno-deprecated-declarations -Wno-pointer-sign -Wno-empty-body" 1>>$LOG 2>&1
		else
		    ./configure --with-php-config=${PREFIX}/php/bin/php-config CFLAGS="-w" 1>>$LOG 2>&1
		fi
        if [ $? != 0 ]; then
            echo 'configure error see '$LOG >> $WF_LOG
        fi
		
		if [ $(uname) == 'Darwin' ]; then
		    make 1>>$LOG 2>&1 && make install 1>>$LOG 2>>$WF_LOG
        else
		    make 1>>$LOG 2>>$WF_LOG && make install 1>>$LOG 2>>$WF_LOG
        fi

        if [ $? != 0 ]; then
            echo 'make error see '$WF_LOG >> $WF_LOG
        fi

		popd >/dev/null

		cp tpl/zlib.ini $PREFIX/php/etc/ext

		echo $? > $ZLIB_INSTALL_STATE
	}&

	ZLIB_IS_DONE="0"
	while :
	do
		for j in '-' '\\' '|' '/'; do
			tput sc
			echo -ne  "Installing zlib, Please wait....... $j"
		    sleep 0.1
		    tput rc
		    
			if [ -s "$WF_LOG" ]; then
				echo "Sth wrong, Please check $LOG and $WF_LOG"
                echo '-' > $ZLIB_INSTALL_STATE
				ZLIB_IS_DONE="2"
				break
			fi
			if [ -f "$ZLIB_INSTALL_STATE" ] && [ $(cat $ZLIB_INSTALL_STATE) != '-' ]; then
				echo "Install zlib Done                          "
                echo '-' > $ZLIB_INSTALL_STATE
				ZLIB_IS_DONE="1"
				break
			fi
		done
		if [ "$ZLIB_IS_DONE" = "1" ] || [ "$ZLIB_IS_DONE" = "2" ]; then
			break
		fi
	done
}

function install_zip(){
	{
		sleep 3

		pushd $PWD >/dev/null
		cd /tmp/php/php* 2>>$WF_LOG

		cd ext/zip 2>>$WF_LOG
		${PREFIX}/php/bin/phpize  1>>$LOG 2>>$WF_LOG
		if [ $(uname) == 'Darwin' ]; then
			./configure --with-php-config=${PREFIX}/php/bin/php-config --with-zlib-dir=/usr/local/opt/zlib/ CFLAGS="-Wno-logical-op-parentheses -Wno-return-type -Wno-macro-redefined -Wno-enum-conversion -Wno-logical-not-parentheses -Wno-tautological-compare -Wno-string-plus-int -Wno-gnu-statement-expression -Wno-absolute-value -Wno-format -Wno-pointer-bool-conversion -Wno-incompatible-pointer-types-discards-qualifiers -Wno-format-extra-args -Wno-format-invalid-specifier -Wno-deprecated-declarations -Wno-pointer-sign -Wno-empty-body" 1>>$LOG 2>&1
		else
		    ./configure --with-php-config=${PREFIX}/php/bin/php-config CFLAGS="-w" 1>>$LOG 2>&1
		fi
        if [ $? != 0 ]; then
            echo 'configure error see '$LOG >> $WF_LOG
        fi
		
		if [ $(uname) == 'Darwin' ]; then
		    make 1>>$LOG 2>&1 && make install 1>>$LOG 2>>$WF_LOG
        else
		    make 1>>$LOG 2>>$WF_LOG && make install 1>>$LOG 2>>$WF_LOG
        fi

        if [ $? != 0 ]; then
            echo 'make error see '$WF_LOG >> $WF_LOG
        fi

		popd >/dev/null

		cp tpl/zip.ini $PREFIX/php/etc/ext

		echo $? > $ZIP_INSTALL_STATE
	}&

	ZIP_IS_DONE="0"
	while :
	do
		for j in '-' '\\' '|' '/'; do
			tput sc
			echo -ne  "Installing zip, Please wait....... $j"
		    sleep 0.1
		    tput rc
		    
			if [ -s "$WF_LOG" ]; then
				echo "Sth wrong, Please check $LOG and $WF_LOG"
                echo '-' > $ZIP_INSTALL_STATE
				ZIP_IS_DONE="2"
				break
			fi
			if [ -f "$ZIP_INSTALL_STATE" ] && [ $(cat $ZIP_INSTALL_STATE) != '-' ]; then
				echo "Install zip Done                          "
                echo '-' > $ZIP_INSTALL_STATE
				ZIP_IS_DONE="1"
				break
			fi
		done
		if [ "$ZIP_IS_DONE" = "1" ] || [ "$ZIP_IS_DONE" = "2" ]; then
			break
		fi
	done
}

function install_logrotate(){
    cp $PWD/logrotate/bin/logrotate ${PREFIX}/bin 2>>$WF_LOG
    cp $PWD/logrotate/conf/logrotate.conf ${PREFIX}/conf/logrotate 2>>$WF_LOG
    
    if [ $(uname) == 'Darwin' ]; then
    	sed -i "" "s|\${PEQ_ROOT}|${PREFIX}|g" ${PREFIX}/conf/logrotate/logrotate.conf 2>>$WF_LOG
    	sed -i "" "s|\${PEQ_ROOT}|${PREFIX}|g" ${PREFIX}/bin/logrotate 2>>$WF_LOG
    else
    	sed -i "s|\${PEQ_ROOT}|${PREFIX}|g" ${PREFIX}/conf/logrotate/logrotate.conf 2>>$WF_LOG
    	sed -i "s|\${PEQ_ROOT}|${PREFIX}|g" ${PREFIX}/bin/logrotate 2>>$WF_LOG
    fi
    
    echo "Install LogRotate Done, Please add to crontabe: \"# 1 * * * * cd ${PREFIX}/bin && bash logrotate -f\""
}

function install_demo(){
	cp -r $PWD/demo/app/* ${PREFIX}/app
	mkdir -p ${PREFIX}/conf/app && cp -r $PWD/demo/conf/app/* ${PREFIX}/conf/app 

	if [ $(uname) == 'Darwin' ]; then
		sed -i "" "s|\${PEQ_ROOT}|${PREFIX}|g" ${PREFIX}/conf/app/helloworld/yaf.ini 2>>$WF_LOG
	else
		sed -i "s|\${PEQ_ROOT}|${PREFIX}|g" ${PREFIX}/conf/app/helloworld/yaf.ini 2>>$WF_LOG
	fi
	cp -r $PWD/demo/webroot/* ${PREFIX}/webroot
      
	echo "Install Demo Done"
}

PREFIX=""

for arg in "$@"
do
	CMD=$(echo $arg | cut -d = -f 1)
	if [ $CMD != "--prefix" ]; then
		echo "unknown opt $CMD"
	else
		PREFIX=$(echo $arg | cut -d = -f 2)
	fi
	
done

if [ ${PREFIX}x == x ]; then
	usage
elif [ ${PREFIX} == "--prefix" ]; then
	echo "Please assign install prefix path!"
fi


mkdir -p ${PREFIX}
mkdir -p ${PREFIX}/app
mkdir -p ${PREFIX}/conf
mkdir -p ${PREFIX}/conf/logrotate
mkdir -p ${PREFIX}/data
mkdir -p ${PREFIX}/data/logrotate
mkdir -p ${PREFIX}/log
mkdir -p ${PREFIX}/log/webserver
mkdir -p ${PREFIX}/log/php
mkdir -p ${PREFIX}/log/logrotate
mkdir -p ${PREFIX}/php
mkdir -p ${PREFIX}/php/etc/ext
cp -r ./phplib ${PREFIX}/php/
mkdir -p ${PREFIX}/webroot
mkdir -p ${PREFIX}/webserver
mkdir -p ${PREFIX}/var
mkdir -p ${PREFIX}/var/nginx
mkdir -p ${PREFIX}/var/php
mkdir -p ${PREFIX}/bin

init

#if [ ! -s "$WF_LOG" ]; then
#    install_nginx
#fi
#if [ ! -s "$WF_LOG" ]; then
#    install_php
#fi
#if [ ! -s "$WF_LOG" ]; then
#    install_yaf
#fi
#if [ ! -s "$WF_LOG" ]; then
#    install_msgpack
#fi
#if [ ! -s "$WF_LOG" ]; then
#   install_redis
#fi
#if [ ! -s "$WF_LOG" ]; then
#    install_curl
#fi
#if [ ! -s "$WF_LOG" ]; then
#    install_mbstring
#fi
if [ ! -s "$WF_LOG" ]; then
    install_phpopenssl
fi
if [ ! -s "$WF_LOG" ]; then
    install_zlib
fi
if [ ! -s "$WF_LOG" ]; then
    install_zip
fi
if [ ! -s "$WF_LOG" ]; then
    install_logrotate
fi
if [ ! -s "$WF_LOG" ]; then
    install_demo
fi

if [ ! -s "$WF_LOG" ]; then
    echo "=====> Install PEQ Done"
fi
