hook_before_init = ""

[Test]
	cluster_name = "Test"
	connect_timeout_ms = 900
	read_timeout_ms = 900
	write_timeout_ms = 900
	retry_times = 1
	charset = "utf8"
	retry_interval_s = 0
	balance_strategy = "Base_DB_RandBalancer"
	username = "tiger"
	password = "1234zh"
	default_db = "electionDb"
	connect_flag = ""
	hook_before_query = ""
	hook_after_query = ""
	hook_on_fail = ""
	hook_on_connect_fail = ""
	
	[Test.host]
		[Test.host.server1]
			ip = "121.42.41.228"
			port = 3306
